// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/human": {
    params: {};
  };
  "/cell/:row/:col": {
    params: {
      "row": string;
      "col": string;
    };
  };
  "/human/:row/:col": {
    params: {
      "row": string;
      "col": string;
    };
  };
  "/methods/:col": {
    params: {
      "col": string;
    };
  };
  "/problem-sets": {
    params: {};
  };
  "/curriculum": {
    params: {};
  };
  "/theory-of-change": {
    params: {};
  };
  "/researchers": {
    params: {};
  };
  "/researchers/:handle": {
    params: {
      "handle": string;
    };
  };
  "/admin": {
    params: {};
  };
  "/admin/papers": {
    params: {};
  };
  "/admin/people": {
    params: {};
  };
  "/fidelity": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/human" | "/cell/:row/:col" | "/human/:row/:col" | "/methods/:col" | "/problem-sets" | "/curriculum" | "/theory-of-change" | "/researchers" | "/researchers/:handle" | "/admin" | "/admin/papers" | "/admin/people" | "/fidelity";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/human.tsx": {
    id: "routes/human";
    page: "/human";
  };
  "routes/cell.tsx": {
    id: "routes/cell";
    page: "/cell/:row/:col";
  };
  "routes/human-cell.tsx": {
    id: "routes/human-cell";
    page: "/human/:row/:col";
  };
  "routes/methods.tsx": {
    id: "routes/methods";
    page: "/methods/:col";
  };
  "routes/problem-sets.tsx": {
    id: "routes/problem-sets";
    page: "/problem-sets";
  };
  "routes/curriculum.tsx": {
    id: "routes/curriculum";
    page: "/curriculum";
  };
  "routes/theory-of-change.tsx": {
    id: "routes/theory-of-change";
    page: "/theory-of-change";
  };
  "routes/researchers.tsx": {
    id: "routes/researchers";
    page: "/researchers";
  };
  "routes/researcher-profile.tsx": {
    id: "routes/researcher-profile";
    page: "/researchers/:handle";
  };
  "routes/admin.tsx": {
    id: "routes/admin";
    page: "/admin" | "/admin/papers" | "/admin/people";
  };
  "routes/admin-scouts.tsx": {
    id: "routes/admin-scouts";
    page: "/admin";
  };
  "routes/admin-papers.tsx": {
    id: "routes/admin-papers";
    page: "/admin/papers";
  };
  "routes/admin-people.tsx": {
    id: "routes/admin-people";
    page: "/admin/people";
  };
  "routes/fidelity.tsx": {
    id: "routes/fidelity";
    page: "/fidelity";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/human": typeof import("./app/routes/human.tsx");
  "routes/cell": typeof import("./app/routes/cell.tsx");
  "routes/human-cell": typeof import("./app/routes/human-cell.tsx");
  "routes/methods": typeof import("./app/routes/methods.tsx");
  "routes/problem-sets": typeof import("./app/routes/problem-sets.tsx");
  "routes/curriculum": typeof import("./app/routes/curriculum.tsx");
  "routes/theory-of-change": typeof import("./app/routes/theory-of-change.tsx");
  "routes/researchers": typeof import("./app/routes/researchers.tsx");
  "routes/researcher-profile": typeof import("./app/routes/researcher-profile.tsx");
  "routes/admin": typeof import("./app/routes/admin.tsx");
  "routes/admin-scouts": typeof import("./app/routes/admin-scouts.tsx");
  "routes/admin-papers": typeof import("./app/routes/admin-papers.tsx");
  "routes/admin-people": typeof import("./app/routes/admin-people.tsx");
  "routes/fidelity": typeof import("./app/routes/fidelity.tsx");
};